permalink: /:year/:month/:day/:title.html
markdown: kramdown
pygments: true

kramdown:
  input: GFM

# 作者信息
author: 
  name: 杨亚梦
  email: mz.yyam@gmail.com
  link: http://private.ilaipi.me
  weibo: http://weibo.com/mz0827
  github: http://github.com/ilaipi

# 站点信息
title: 杨亚梦的博客
description: 杨亚梦的博客
url: http://ilaipi.me
rss_url: /pages/atom.xml

# avatar头像及Favicon
avatar: http://7xiato.com1.z0.glb.clouddn.com/avatar.jpeg
favicon: http://7xiato.com1.z0.glb.clouddn.com/favicon.ico

# google analytics 设置
#ga:
#  id: UA-54767140-1
#  url: yansu.org

# disqus 设置
disqus:
  shortname: ilaipi
