permalink: /:year/:month/:day/:title.html
markdown: kramdown
pygments: true

kramdown:
  input: GFM

# 作者信息
author: 
  name: 杨亚梦
  email: mz.yyam@gmail.com
  link: http://yyam.me
  weibo: http://weibo.com/mz0827
  github: http://github.com/mz0827

# 站点信息
title: 杨亚梦的博客
description: 杨亚梦的博客
url: http://yyam.me
rss_url: /pages/atom.xml

# avatar头像及Favicon
avatar: http://gravatar.duoshuo.com/avatar/8bdc782a9138d7410c5fa5b2c43f6e18.png
favicon: http://7u2ho6.com1.z0.glb.clouddn.com/site-favicon.ico

# google analytics 设置
ga:
  id: UA-54767140-1
  url: yansu.org

# disqus 设置
disqus:
  shortname: yyam